[package]
name = "hakai/roblox-asset-reuploader-plugin"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusion = "elttob/fusion@0.2.0"
synthetic-fusion = "nightcycle/synthetic-fusion@9.3.8"
